// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:935812111525:web:eb1eb0596d71e848d4814c',
    messagingSenderId: '935812111525',
    projectId: 'fyp2facedetection',
    authDomain: 'fyp2facedetection.firebaseapp.com',
    databaseURL:
        'https://fyp2facedetection-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp2facedetection.firebasestorage.app',
    measurementId: 'G-0TQXXR17VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:935812111525:android:08c93c89805a4cfbd4814c',
    messagingSenderId: '935812111525',
    projectId: 'fyp2facedetection',
    databaseURL:
        'https://fyp2facedetection-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp2facedetection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:935812111525:ios:19e2e91150bfd58fd4814c',
    messagingSenderId: '935812111525',
    projectId: 'fyp2facedetection',
    databaseURL:
        'https://fyp2facedetection-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp2facedetection.firebasestorage.app',
    iosBundleId: 'com.example.yolodetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:935812111525:ios:19e2e91150bfd58fd4814c',
    messagingSenderId: '935812111525',
    projectId: 'fyp2facedetection',
    databaseURL:
        'https://fyp2facedetection-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp2facedetection.firebasestorage.app',
    iosBundleId: 'com.example.yolodetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:935812111525:web:0cbfa583e4bdd5c5d4814c',
    messagingSenderId: '935812111525',
    projectId: 'fyp2facedetection',
    authDomain: 'fyp2facedetection.firebaseapp.com',
    databaseURL:
        'https://fyp2facedetection-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp2facedetection.firebasestorage.app',
    measurementId: 'G-2BGQB4D6ND',
  );
}
